name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Remove the Node.js setup and npm ci steps

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch the action should deploy to
          folder: . # The folder to deploy (usually your built site)
          token: ${{ secrets.GITHUB_TOKEN }} # GitHub automatically provides this token
