name: Update README with Spotify data

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '0 * * * *'  # Run every 6 hours
    
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_ACTION_ACCESS }}  # Use your secret name here
      
      - name: Update README with Spotify data
        run: |
          # Read the Spotify data file
          SPOTIFY_CONTENT=$(cat .github/variables/spotify-recently-played.md)
          
          # Use awk to replace content between markers in README.md
          awk -v spotify="$SPOTIFY_CONTENT" '
          BEGIN { p=1 }
          /<!-- SPOTIFY-RECENTLY-PLAYED:START -->/ { print; print spotify; p=0 }
          /<!-- SPOTIFY-RECENTLY-PLAYED:END -->/ { p=1 }
          p' README.md > README.tmp
          
          # Restore the end marker
          echo "<!-- SPOTIFY-RECENTLY-PLAYED:END -->" >> README.tmp
          
          # Replace the original file
          mv README.tmp README.md
          
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add README.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update README with latest Spotify data" && git push)
