name: variable-2-README-workflow

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes
    
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_ACTION_ACCESS }}  # Use your secret name here
      
      - name: variable-2-README-workflow
        run: |
          # Read the Spotify data file and remove the "Updated via N8N workflow" text
          SPOTIFY_CONTENT=$(cat .github/variables/spotify-recently-played.md | sed 's/<sub><i>Updated via N8N workflow<\/i><\/sub>//g')
          
          # First, clean up the README.md to remove duplicate tags
          # Create a temporary file with just one set of markers
          grep -v "<!-- SPOTIFY_RECENTLY_PLAYED:START -->" README.md | grep -v "<!-- SPOTIFY_RECENTLY_PLAYED:END -->" > README.cleaned.md
          
          # Now use awk to replace content between the markers
          awk -v spotify="$SPOTIFY_CONTENT" '
          BEGIN { p=1 }
          /<!-- SPOTIFY-RECENTLY-PLAYED:START -->/ { print; print spotify; p=0 }
          /<!-- SPOTIFY-RECENTLY-PLAYED:END -->/ { p=1; print; next }
          p' README.cleaned.md > README.tmp
          
          # Replace the original file and clean up
          mv README.tmp README.md
          rm README.cleaned.md
          
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add README.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "automated-variable-2-README-workflow" && git push)
